# Generated by Django 4.2 on 2024-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('dbms', models.JSONField()),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('under_attack', models.CharField(max_length=5)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
